feature/SPRIND-31_musap-kms
Sphereon-Opensource/mobile-wallet pull request #200
Opened 2024-08-06 13:29 UTC by sanderPostma

Integrate MUSAP KMS into mobile wallet

2024-08-06 14:50 UTC, nklomp requested changes
Stopped review.

Why is the wallet doing all the changes that the RN package should be doing itself?

2024-08-06 14:50 UTC, nklomp commented on android/app/build.gradle
> +    maven {
Why is this being solved in here instead of in the RN module itself?

2024-08-06 14:50 UTC, nklomp commented on android/app/src/main/java/com/sphereon/ssi/wallet/MainApplication.kt
> +                    try {
Same as above. The wallet should not be handling this. The RN package should

2024-08-06 15:00 UTC, sanderPostma commented on android/app/src/main/java/com/sphereon/ssi/wallet/MainApplication.kt
> +                    try {
In the React Native app I did not have to do this, for the expo app I do for reasons I don't know atm.

2024-08-06 15:41 UTC, sanderPostma commented on android/app/build.gradle
> +    maven {
I've tried different ways, adding file repositories in them in the module's build.gradle doesn't seem te work. 
Considering the time we've already spent on this, I focused on getting it to work for our wallet for now.

2024-08-06 16:19 UTC, sanderPostma commented on android/app/src/main/java/com/sphereon/ssi/wallet/MainApplication.kt
> +                    try {
I can try to create an expo wrapper on the mac (since I can't create an expo lib on Windows,) but that will eat up more time.

2024-08-06 16:22 UTC, nklomp commented on android/app/src/main/java/com/sphereon/ssi/wallet/MainApplication.kt
> +                    try {
Yes but then at least create confluence page with things that need to be changed and create tickets linking to it. The credential store and Musap KMS are things we need long term, not PoC

2024-08-06 16:22 UTC, nklomp commented on android/app/build.gradle
> +    maven {
Yes but then at least create confluence page with things that need to be changed and create tickets linking to it. The credential store and Musap KMS are things we need long term, not PoC

2024-08-08 15:15 UTC, sanderPostma commented on android/app/build.gradle
> +    maven {
Created VDX-337 for now

2024-08-08 15:15 UTC, sanderPostma commented on android/app/src/main/java/com/sphereon/ssi/wallet/MainApplication.kt
> +                    try {
VDX-337

2024-08-27 09:06 UTC, merged