(WIP) ios pod update, nfc modal implementation, merge with stepper updates
Sphereon-Opensource/mobile-wallet pull request #206
Opened 2024-08-08 12:46 UTC by merveillevaneck

2024-08-09 08:39 UTC, BtencateSphereon requested changes
the ticket is about implementing whole step 3, so we are missing some screens and implementation in this PR

2024-08-09 08:39 UTC, BtencateSphereon commented on src/assets/images/ausweis_icon.png
i would suggest adding images as svg

2024-08-09 08:39 UTC, BtencateSphereon commented on src/localization/translations/en.json
> +  "import_data_title": "Import personal data",
where are the dutch localizations? it is fine adding them to the dutch file in english for now. so no need to translate it to dutch. but just make sure thy are present so we know which ones we still need to translate

2024-08-09 08:39 UTC, BtencateSphereon commented on src/screens/Onboarding/ImportPersonalDataSCreen/index.tsx
> +export const AusweisEPinModal = (props: AusweisEPinModalProps) => {
please move this to it's own file

2024-08-09 08:39 UTC, BtencateSphereon commented on src/screens/Onboarding/ImportPersonalDataSCreen/index.tsx
> +export const AusweisScanModal = (props: AusweisScanModalProps) => {
please move this to it's own file

2024-08-13 23:06 UTC, merveillevaneck commented
closing because of syncing updates with newly merged `feat/new-onboarding` so rebased on top of funke and continued there addressing above comments as well as adding more UI

2024-08-20 21:14 UTC, merged