fix/c2 flow fixes
Sphereon-Opensource/mobile-wallet pull request #278
Opened 2024-09-27 13:15 UTC by BtencateSphereon

2024-09-27 14:46 UTC, nklomp approved these changes

2024-09-27 14:51 UTC, nklomp requested changes
Not sure the C flow still works mainly when sharing with a RP. If you ask me the static kmsKeyRef will cause issues

2024-09-27 14:51 UTC, nklomp commented on src/services/pexService.ts
> +      kmsKeyRef: 'https://demo.pid-issuer.bundesdruckerei.de/c2/.well-known/openid-credential-issuer',
How does this work when using the regular C flow?

2024-10-01 07:35 UTC, BtencateSphereon commented on src/services/pexService.ts
> +      kmsKeyRef: 'https://demo.pid-issuer.bundesdruckerei.de/c2/.well-known/openid-credential-issuer',
not ignored, but i am waiting on a new ssi-sdk version to test everything

2024-10-01 12:13 UTC, BtencateSphereon commented on src/services/pexService.ts
> +      kmsKeyRef: 'https://demo.pid-issuer.bundesdruckerei.de/c2/.well-known/openid-credential-issuer',
Seems to be working for in all flows. but i made it a condition to only set the kmsKeyRef for the c2 flow. would that be ok for now?

2024-10-01 12:45 UTC, merged