feature/SPRIND-92
Sphereon-Opensource/mobile-wallet pull request #291
Opened 2024-10-30 15:31 UTC by BtencateSphereon

2024-10-31 09:42 UTC, sanderPostma requested changes

2024-10-31 09:42 UTC, sanderPostma commented on package.json
> +    "@sphereon/ssi-sdk.agent-config": "0.30.2-feature.SPRIND.92.149",
Don't forget to updated after https://github.com/Sphereon-Opensource/SSI-SDK/pull/259 is merged

2024-10-31 09:42 UTC, sanderPostma commented on src/migrations/1730209432321-AddTrustAnchorContacts.ts
> +    return Promise.reject(Error('Not yet implemented'));
This is something AI can do flawlessly
```
import { QueryRunner } from 'typeorm';

export class AddTrustAnchorContacts1730209432321 implements MigrationInterface {
  // ... existing up() method remains the same ...

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Delete Findynet Federation related records
    await queryRunner.query(
      `DELETE FROM "BaseLocaleBranding" WHERE id = '8c66b536-eb30-45f8-8ed0-2f4a2203c16f'`
    );
    
    await queryRunner.query(
      `DELETE FROM "ImageAttributes" WHERE id = '154f90c0-2135-439e-b23d-458e3d781589'`
    );
    
    await queryRunner.query(
      `DELETE FROM "ImageDimensions" WHERE id = 'e17767fc-91b8-4546-af34-91305c89571d'`
    );
    
    await queryRunner.query(
      `DELETE FROM "IssuerBranding" WHERE id = 'e6523745-aa00-43ee-8c92-d352243c64b1'`
    );
    
    await queryRunner.query(
      `DELETE FROM "CorrelationIdentifier" WHERE id = 'd56bb8f2-db52-4923-a4ff-9e835e16290c'`
    );
    
    await queryRunner.query(
      `DELETE FROM "Identity" WHERE id = '8cea5ccd-59bf-4c72-9844-ddfcfdf6ca56'`
    );
    
    await queryRunner.query(
      `DELETE FROM "BaseContact" WHERE id = '7e585fee-7f7e-469d-8c99-96a7ec3e60e4'`
    );
    
    await queryRunner.query(
      `DELETE FROM "Party" WHERE id = '7f16a97f-19e8-4387-bcac-a23f82797f8f'`
    );

    // Delete Sphereon Federation related records
    await queryRunner.query(
      `DELETE FROM "BaseLocaleBranding" WHERE id = 'd969e748-1ae7-45df-8638-a716350869d5'`
    );
    
    await queryRunner.query(
      `DELETE FROM "ImageAttributes" WHERE id = '19803a99-8d0a-4fe8-8565-278032b7903b'`
    );
    
    await queryRunner.query(
      `DELETE FROM "ImageDimensions" WHERE id = '3f38b5b9-bf7c-4eab-91c4-6970578b9d3a'`
    );
    
    await queryRunner.query(
      `DELETE FROM "IssuerBranding" WHERE id = '999ae111-6d66-46da-ac01-858d1df87a83'`
    );
    
    await queryRunner.query(
      `DELETE FROM "CorrelationIdentifier" WHERE id = '2b4130d5-bc01-4428-9f8e-8ff1e536f666'`
    );
    
    await queryRunner.query(
      `DELETE FROM "Identity" WHERE id = '66b16b8c-cf94-449c-820d-fd888dec7a88'`
    );
    
    await queryRunner.query(
      `DELETE FROM "BaseContact" WHERE id = '0014e6b8-9271-4d4a-939c-dd1b23880f4d'`
    );
    
    await queryRunner.query(
      `DELETE FROM "Party" WHERE id = '654d698e-fd26-4ac7-8098-7e14870140df'`
    );
  }
}
```

2024-10-31 09:45 UTC, sanderPostma approved these changes
LGTM
the comments are FYI

2024-11-04 14:33 UTC, BtencateSphereon commented on src/migrations/1730209432321-AddTrustAnchorContacts.ts
> +    return Promise.reject(Error('Not yet implemented'));
hmmm yes, but these are temp migrations just so for now i am leaving it. but sure, easy enough for an AI

2024-11-06 10:33 UTC, merged