feature/SPRIND-116
Sphereon-Opensource/mobile-wallet pull request #315
Opened 2024-11-20 15:28 UTC by zoemaas

2025-01-09 14:53 UTC, sanderPostma requested changes

2025-01-09 14:53 UTC, sanderPostma commented on src/types/machines/siopV2/index.ts
> +  federation_entity?: any
Can't federation_entity have a type here?

2025-01-13 09:02 UTC, sanderPostma commented on package.json
> +    "@sphereon/ssi-sdk-ext.identifier-resolution": "file:../SSI-SDK-crypto-extensions/packages/identifier-resolution",
Do not forget to revert to a real version before merge

2025-01-14 15:51 UTC, zoemaas commented on src/types/machines/siopV2/index.ts
> +  federation_entity?: any
Yes and no. Yes because we have an @sphereon/openid-federation-open-api and no because the library does not contain the openid federation types. Since duplication is not a good choice, I opened a bug ticket to fix this.

2025-01-14 16:38 UTC, zoemaas commented on package.json
> +    "@sphereon/ssi-sdk-ext.identifier-resolution": "file:../SSI-SDK-crypto-extensions/packages/identifier-resolution",
Updated to use the package from the remote npm registry

2025-01-16 08:43 UTC, sanderPostma approved these changes

2025-01-16 12:10 UTC, merged